// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "FrancisChoi",
            "url": "https://github.com/FrancisChoi02/"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/chat/history": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取聊天记录接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "聊天相关接口"
                ],
                "summary": "获取聊天记录",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "接收方用户 ID",
                        "name": "to_user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "消息发送成功",
                        "schema": {
                            "$ref": "#/definitions/model.Message"
                        }
                    }
                }
            }
        },
        "/douyin/comment/action/": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "用户对视频进行评论的接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论相关接口"
                ],
                "summary": "用户对视频进行评论",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "需要评论操作的视频 Id",
                        "name": "video_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "操作类型，1 表示添加评论，2 表示删除评论",
                        "name": "action_type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "评论内容，当 action_type 为 1 时必填",
                        "name": "comment_text",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "$ref": "#/definitions/model.CommentActionResponse"
                        }
                    },
                    "400": {
                        "description": "用户 ID 错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/douyin/comment/list/": {
            "get": {
                "responses": {}
            }
        },
        "/douyin/favorite/action/": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "用户点赞操作接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频相关接口"
                ],
                "summary": "用户点赞操作",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "视频 ID",
                        "name": "video_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "操作类型，1表示点赞，2表示取消点赞",
                        "name": "action_type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/douyin/favorite/list/": {
            "get": {
                "description": "获取用户的喜欢视频列表接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频相关接口"
                ],
                "summary": "获取用户的喜欢视频列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户 ID",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "用户 ID 错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器忙，请稍后重试",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/douyin/feed/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Feed"
                ],
                "summary": "获取视频流",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "最新时间戳，单位秒",
                        "name": "latest_time",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "登录token",
                        "name": "token",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求成功",
                        "schema": {
                            "$ref": "#/definitions/model.FeedResponse"
                        }
                    }
                }
            }
        },
        "/douyin/message/action/": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "发送聊天信息接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "聊天相关接口"
                ],
                "summary": "发送聊天信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "接收方用户 ID",
                        "name": "to_user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "消息操作类型",
                        "name": "action_type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "消息内容",
                        "name": "content",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "消息发送成功",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/douyin/publish/action": {
            "post": {
                "description": "用户投稿视频",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Video"
                ],
                "summary": "视频投稿",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "视频文件",
                        "name": "video",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "视频封面",
                        "name": "cover",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "视频标题",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "视频描述",
                        "name": "desc",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "视频分类ID",
                        "name": "category_id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"OK\",\"data\":null}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"code\":400,\"msg\":\"请求参数错误\",\"data\":null}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "{\"code\":401,\"msg\":\"未登录或Token过期\",\"data\":null}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"msg\":\"服务器内部错误\",\"data\":null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/douyin/publish/list/": {
            "get": {
                "description": "根据用户ID获取视频列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Video"
                ],
                "summary": "获取指定用户的视频列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.VideoListResponse"
                        }
                    }
                }
            }
        },
        "/douyin/relation/action/": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "用户关系操作接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "关注相关接口"
                ],
                "summary": "用户关系操作",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "接收方用户 ID",
                        "name": "to_user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "操作类型，1表示关注，2表示取消关注",
                        "name": "action_type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/douyin/relation/action/friend/list/": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取用户聊天好友列表接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "好友相关接口"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户 ID",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "好友列表",
                        "schema": {
                            "$ref": "#/definitions/model.FriendListResponse"
                        }
                    }
                }
            }
        },
        "/douyin/relation/follower/list/": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取用户关注列表接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "关注相关接口"
                ],
                "summary": "获取用户关注列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户 ID",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "关注列表",
                        "schema": {
                            "$ref": "#/definitions/model.FollowRelationResponse"
                        }
                    }
                }
            }
        },
        "/douyin/user/": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "查询指定用户信息的接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关接口"
                ],
                "summary": "查询用户信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户 ID",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询到的用户信息",
                        "schema": {
                            "$ref": "#/definitions/model.UserInfoResponse"
                        }
                    }
                }
            }
        },
        "/douyin/user/login/": {
            "get": {
                "description": "用户登录接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关接口"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.UserDetailResponse"
                        }
                    }
                }
            }
        },
        "/douyin/user/register/": {
            "post": {
                "description": "用户注册接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关接口"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.UserDetailResponse"
                        }
                    }
                }
            }
        },
        "/relation/fans": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取用户粉丝列表接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "关注相关接口"
                ],
                "summary": "获取用户粉丝列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户 ID",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "关注粉丝列表",
                        "schema": {
                            "$ref": "#/definitions/model.FollowRelationResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.CommentActionResponse": {
            "type": "object",
            "properties": {
                "comment": {
                    "description": "返回评论结果",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.CommentResponse"
                        }
                    ]
                },
                "status_code": {
                    "description": "状态码，0-成功，其他值-失败",
                    "type": "integer"
                },
                "status_msg": {
                    "description": "返回状态描述",
                    "type": "string"
                }
            }
        },
        "model.CommentResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "create_date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "user": {
                    "$ref": "#/definitions/model.UserResponse"
                }
            }
        },
        "model.FeedResponse": {
            "type": "object",
            "properties": {
                "next_timet": {
                    "description": "下一次视频刷新时间",
                    "type": "integer"
                },
                "status_code": {
                    "description": "状态码，0-成功，其他值-失败",
                    "type": "integer"
                },
                "status_msg": {
                    "description": "返回状态描述",
                    "type": "string"
                },
                "video_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.VideoResponse"
                    }
                }
            }
        },
        "model.FollowRelationResponse": {
            "type": "object",
            "properties": {
                "status_code": {
                    "description": "状态码，0-成功，其他值-失败",
                    "type": "integer"
                },
                "status_msg": {
                    "description": "返回状态描述",
                    "type": "string"
                },
                "user_list": {
                    "description": "返回用户列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.UserResponse"
                    }
                }
            }
        },
        "model.FriendListResponse": {
            "type": "object",
            "properties": {
                "status_code": {
                    "description": "状态码，0-成功，其他值-失败",
                    "type": "integer"
                },
                "status_msg": {
                    "description": "返回状态描述",
                    "type": "string"
                },
                "user_list": {
                    "description": "返回聊天好友列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.FriendResponse"
                    }
                }
            }
        },
        "model.FriendResponse": {
            "type": "object",
            "properties": {
                "favorite_count": {
                    "type": "integer"
                },
                "follow_count": {
                    "type": "integer"
                },
                "follower_count": {
                    "type": "integer"
                },
                "is_follow": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                },
                "msgType": {
                    "description": "message消息的类型，0 =\u003e 当前请求用户接收的消息， 1 =\u003e 当前请求用户发送的消息",
                    "type": "integer"
                },
                "total_favorited": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                },
                "work_count": {
                    "type": "integer"
                }
            }
        },
        "model.Message": {
            "type": "object",
            "properties": {
                "comment_id": {
                    "type": "integer"
                },
                "comment_text": {
                    "type": "string"
                },
                "create_time": {
                    "type": "string"
                },
                "from_user_id": {
                    "type": "integer"
                },
                "to_user_id": {
                    "type": "integer"
                }
            }
        },
        "model.UserDetailResponse": {
            "type": "object",
            "properties": {
                "status_code": {
                    "description": "状态码，0-成功，其他值-失败",
                    "type": "integer"
                },
                "status_msg": {
                    "description": "返回状态描述",
                    "type": "string"
                },
                "token": {
                    "description": "用户鉴权token",
                    "type": "string"
                },
                "user_id": {
                    "description": "用户id",
                    "type": "integer"
                }
            }
        },
        "model.UserInfoResponse": {
            "type": "object",
            "properties": {
                "status_code": {
                    "description": "状态码，0-成功，其他值-失败",
                    "type": "integer"
                },
                "status_msg": {
                    "description": "返回状态描述",
                    "type": "string"
                },
                "user": {
                    "description": "返回用户信息反馈结构体",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.UserResponse"
                        }
                    ]
                }
            }
        },
        "model.UserResponse": {
            "type": "object",
            "properties": {
                "favorite_count": {
                    "type": "integer"
                },
                "follow_count": {
                    "type": "integer"
                },
                "follower_count": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "is_follow": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "total_favorited": {
                    "type": "integer"
                },
                "work_count": {
                    "type": "integer"
                }
            }
        },
        "model.VideoListResponse": {
            "type": "object",
            "properties": {
                "status_code": {
                    "description": "状态码，0-成功，其他值-失败",
                    "type": "integer"
                },
                "status_msg": {
                    "description": "返回状态描述",
                    "type": "string"
                },
                "video_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.VideoResponse"
                    }
                }
            }
        },
        "model.VideoResponse": {
            "type": "object",
            "properties": {
                "author": {
                    "$ref": "#/definitions/model.UserResponse"
                },
                "comment_count": {
                    "type": "integer"
                },
                "cover_url": {
                    "type": "string"
                },
                "create_time": {
                    "type": "integer"
                },
                "favorite_count": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "is_favorite": {
                    "type": "boolean"
                },
                "play_url": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:8080",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Team2048_Tiktok 项目接口文档",
	Description:      "极简版抖音",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
